"use strict";

import type { CurrencyCode } from "../../types.js";

export function buildResetConfiguration(defaultCurrency: CurrencyCode): Record<string, unknown> {
  return {
    subscribed: false,
    notificationChannelId: null,
    pendingUpdates: {},
    discountsSubscribed: false,
    discountChannelId: null,
    pendingDiscounts: [],
    minDiscountPercent: 70,
    includeFreeGames: true,
    includePaidDiscounts: true,
    notificationMode: "detailed",
    updateMessageTemplate: null,
    discountMessageTemplate: null,
    currency: defaultCurrency,
    outboxRecoveryVerify: false,
    lastProcessedGameKey: null,
    seenHashVersionUpdates: 0,
    seenHashVersionDiscounts: 0,
    updatesInitializing: false,
    updatesActivationId: null,
    updatesLastError: { message: "", channelId: null, at: null },
    discountsInitializing: false,
    discountsActivationId: null,
    discountsLastError: { message: "", channelId: null, at: null },
    enabledGames: [],
    commandSnoozes: {},
    enabledStores: [],
    maxAbsolutePrice: 0,
    notificationRoleId: null,
    discountRoleId: null,
    adminAlertChannelId: null,
    priceAlerts: [],
    youtubeChannels: [],
    youtubeNotificationChannelId: null,
    youtubeNotificationsEnabled: false,
    youtubeHasActivated: false,
    youtubeFilters: {
      excludeShorts: true,
      excludeLives: true,
      excludePremieres: true,
      minDurationSeconds: 0
    },
    youtubeMessageTemplate: null,
    youtubeChannelRoutes: [],
    youtubeTitleIncludeWords: [],
    watchlistGameSuggestions: [],
    playerCountSubscribed: false,
    playerCountChannelId: null,
    playerCountGames: [],
    playerCountInitializing: false,
    playerCountActivationId: null,
    playerCountWatchState: [],
    futureReleaseGames: [],
    adminCommandAccess: null,
    adminCommandAccessByCommand: {},
    futureReleaseSubscribed: false,
    futureReleaseChannelId: null,
    futureReleaseInitializing: false,
    futureReleaseActivationId: null,
    dlcSubscribed: false,
    dlcChannelId: null,
    dlcInitializing: false,
    dlcActivationId: null,
    newAccountAlertChannelId: null,
    newAccountAlertsEnabled: false,
    threatAlertChannelId: null,
    threatProtectionEnabled: false,
    botAddAlertChannelId: null,
    permissionRequestChannelId: null,
    antiRaidAlertChannelId: null,
    antiRaidThresholds: null,
    antiRaidDryRunEnabled: false,
    moderationGuardEnabled: false,
    botAddProtectionEnabled: false,
    warningChannelId: null,
    botAddPermissions: [],
    purgeAmount: 50,
    lockedChannelIds: [],
    lockedChannelPermissions: []
  };
}
