[workspace]
members = ["core", "inspector", "mspack-sys"]

[package]
name = "discord_patch_bot_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
discord_patch_bot_logic = { path = "core" }
napi = { version = "3", default-features = false, features = ["napi4"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"
