import type { SlashCommandJsonSource, SlashDefinitionTools } from "./slashDefinitionTools.js";

export function buildAdminCommandDefinitions({ SlashCommandBuilder, PermissionsBitField, CURRENCY_CHOICES }: SlashDefinitionTools): SlashCommandJsonSource[] {
  return [
    new SlashCommandBuilder()
      .setName("add")
      .setDescription("Adauga ceva (alerta de pret, joc in watchlist, backup, sugestie de comanda)")
      .addSubcommand(subcommand => subcommand.setName("price-alert").setDescription("Adauga sau actualizeaza o alerta de pret (admin)")
        .addStringOption(option => option.setName("joc").setDescription("Cheia jocului").setRequired(true).setAutocomplete(true))
        .addNumberOption(option => option.setName("price").setDescription("Pragul de pret").setRequired(true).setMinValue(0.01).setMaxValue(10000))
        .addStringOption(option => option.setName("currency").setDescription("Valuta pragului").setRequired(true).addChoices(...CURRENCY_CHOICES)))
      .addSubcommand(subcommand => subcommand.setName("watchlist").setDescription("Adauga un joc in watchlist (admin)")
        .addStringOption(option => option.setName("joc").setDescription("Cheia jocului").setRequired(true).setAutocomplete(true)))
      .addSubcommand(subcommand => subcommand.setName("backup").setDescription("Salveaza configuratia curenta intr-un backup (admin)")
        .addStringOption(option => option.setName("name").setDescription("Numele backup-ului").setRequired(true).setMaxLength(64)))
      .addSubcommand(subcommand => subcommand.setName("suggestion").setDescription("Propune o comanda noua")
        .addStringOption(option => option.setName("name").setDescription("Numele comenzii propuse").setRequired(true).setMaxLength(80))
        .addStringOption(option => option.setName("description").setDescription("Ce ar trebui sa faca aceasta comanda").setRequired(true).setMaxLength(500))),
    new SlashCommandBuilder()
      .setName("remove")
      .setDescription("Scoate ceva (alerta de pret, joc din watchlist)")
      .addSubcommand(subcommand => subcommand.setName("price-alert").setDescription("Sterge alertele de pret ale unui joc (admin)")
        .addStringOption(option => option.setName("joc").setDescription("Cheia jocului").setRequired(true).setAutocomplete(true)))
      .addSubcommand(subcommand => subcommand.setName("watchlist").setDescription("Scoate un joc din watchlist (admin)")
        .addStringOption(option => option.setName("joc").setDescription("Cheia jocului").setRequired(true).setAutocomplete(true))),
    new SlashCommandBuilder()
      .setName("delete")
      .setDescription("Sterge configurari owner-only ale botului")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("admin-command-access").setDescription("Sterge regula de rol pentru comenzile admin")
        .addBooleanOption(option => option.setName("confirm").setDescription("Confirma revenirea la accesul implicit").setRequired(true))
        .addStringOption(option => option.setName("command").setDescription("Comanda/pachetul pentru care stergi regula (gol = global)").setRequired(false).setAutocomplete(true))),
    new SlashCommandBuilder()
      .setName("config")
      .setDescription("Afiseaza configuratia curenta a serverului (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString()),
    new SlashCommandBuilder()
      .setName("backup")
      .setDescription("Gestioneaza backup-uri ale configuratiei botului pentru server (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("list").setDescription("Listeaza backup-urile salvate"))
      .addSubcommand(subcommand => subcommand.setName("preview").setDescription("Arata ce setari, canale si roluri restaureaza backup-ul")
        .addStringOption(option => option.setName("name").setDescription("Numele backup-ului").setRequired(true).setMaxLength(64)))
      .addSubcommand(subcommand => subcommand.setName("load").setDescription("Incarca un backup salvat")
        .addStringOption(option => option.setName("name").setDescription("Numele backup-ului").setRequired(true).setMaxLength(64))
        .addBooleanOption(option => option.setName("confirm").setDescription("Confirma incarcarea backup-ului").setRequired(true)))
      .addSubcommand(subcommand => subcommand.setName("delete").setDescription("Sterge un backup salvat")
        .addStringOption(option => option.setName("name").setDescription("Numele backup-ului").setRequired(true).setMaxLength(64))
        .addBooleanOption(option => option.setName("confirm").setDescription("Confirma stergerea backup-ului").setRequired(true))),
    new SlashCommandBuilder()
      .setName("bot-log")
      .setDescription("Afiseaza ultimele comenzi admin executate pe server (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("recent").setDescription("Afiseaza cele mai recente comenzi admin")
        .addIntegerOption(option => option.setName("numar").setDescription("Cate intrari (1-25, implicit 10)").setRequired(false).setMinValue(1).setMaxValue(25)))
      .addSubcommand(subcommand => subcommand.setName("older").setDescription("Afiseaza comenzi admin dintr-un interval istoric")
        .addStringOption(option => option.setName("period").setDescription("Intervalul permis").setRequired(true)
          .addChoices({ name: "zi", value: "zi" }, { name: "saptamana", value: "saptamana" }, { name: "luna", value: "luna" }))
        .addStringOption(option => option.setName("start").setDescription("YYYY-MM-DD pentru zi/saptamana sau YYYY-MM pentru luna").setRequired(true))
        .addIntegerOption(option => option.setName("offset").setDescription("De unde incepe urmatorul lot de 25").setRequired(false).setMinValue(0).setMaxValue(1000))),
    new SlashCommandBuilder()
      .setName("server-log")
      .setDescription("Afiseaza ultimele schimbari importante salvate pentru server (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("recent").setDescription("Afiseaza cele mai recente schimbari server")
        .addIntegerOption(option => option.setName("numar").setDescription("Cate intrari (1-25, implicit 10)").setRequired(false).setMinValue(1).setMaxValue(25)))
      .addSubcommand(subcommand => subcommand.setName("older").setDescription("Afiseaza schimbari server dintr-un interval istoric")
        .addStringOption(option => option.setName("period").setDescription("Intervalul permis").setRequired(true)
          .addChoices({ name: "zi", value: "zi" }, { name: "saptamana", value: "saptamana" }, { name: "luna", value: "luna" }))
        .addStringOption(option => option.setName("start").setDescription("YYYY-MM-DD pentru zi/saptamana sau YYYY-MM pentru luna").setRequired(true))
        .addIntegerOption(option => option.setName("offset").setDescription("De unde incepe urmatorul lot de 25").setRequired(false).setMinValue(0).setMaxValue(1000))),
    new SlashCommandBuilder()
      .setName("reset-config")
      .setDescription("Reseteaza toate setarile botului pentru server (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addBooleanOption(option => option.setName("confirm").setDescription("Confirma resetarea completa").setRequired(true)),
    new SlashCommandBuilder()
      .setName("admin-alerts")
      .setDescription("Configureaza canalul alertelor administrative (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("set").setDescription("Seteaza canalul pentru alerte administrative")
        .addChannelOption(option => option.setName("channel").setDescription("Canalul pentru alerte").setRequired(true)))
      .addSubcommand(subcommand => subcommand.setName("off").setDescription("Opreste alertele administrative Discord")),
    new SlashCommandBuilder()
      .setName("admin-command-access")
      .setDescription("Afiseaza regula de acces prin rol pentru comenzile admin (owner-only)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("list").setDescription("Afiseaza regula curenta pentru acces admin prin rol")
        .addStringOption(option => option.setName("command").setDescription("Comanda/pachetul admin de verificat (gol = toate)").setRequired(false).setAutocomplete(true))),
    new SlashCommandBuilder()
      .setName("maintenance")
      .setDescription("Afiseaza problemele operationale care trebuie verificate (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString()),
    new SlashCommandBuilder()
      .setName("snooze")
      .setDescription("Pune temporar pe pauza o comanda a botului (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addStringOption(option => option.setName("command").setDescription("Comanda de pus pe pauza").setRequired(true).setAutocomplete(true))
      .addStringOption(option => option.setName("durata").setDescription("Durata pauzei, de exemplu 30m, 2h sau 1d").setRequired(true)),
    new SlashCommandBuilder()
      .setName("unsnooze")
      .setDescription("Scoate pauza temporara de pe o comanda a botului (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addStringOption(option => option.setName("command").setDescription("Comanda de repornit").setRequired(true).setAutocomplete(true)),
    new SlashCommandBuilder()
      .setName("set")
      .setDescription("Configureaza preferintele serverului (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("mode").setDescription("Mod afisare embed")
        .addStringOption(option => option.setName("value").setDescription("compact sau detailed").setRequired(true)
          .addChoices({ name: "compact", value: "compact" }, { name: "detailed", value: "detailed" })))
      .addSubcommand(subcommand => subcommand.setName("mindiscount").setDescription("Procent minim reducere (0-100)")
        .addIntegerOption(option => option.setName("value").setDescription("0-100").setRequired(true).setMinValue(0).setMaxValue(100)))
      .addSubcommand(subcommand => subcommand.setName("maxprice").setDescription("Pret maxim absolut pentru oferte (0 = fara limita)")
        .addIntegerOption(option => option.setName("value").setDescription("0-10000 (0 = dezactivat)").setRequired(true).setMinValue(0).setMaxValue(10000)))
      .addSubcommand(subcommand => subcommand.setName("free").setDescription("Afiseaza jocurile gratuite?")
        .addStringOption(option => option.setName("value").setDescription("on/off").setRequired(true)
          .addChoices({ name: "on", value: "on" }, { name: "off", value: "off" })))
      .addSubcommand(subcommand => subcommand.setName("paid").setDescription("Afiseaza ofertele platite?")
        .addStringOption(option => option.setName("value").setDescription("on/off").setRequired(true)
          .addChoices({ name: "on", value: "on" }, { name: "off", value: "off" })))
      .addSubcommand(subcommand => subcommand.setName("currency").setDescription("Valuta pentru afisarea preturilor")
        .addStringOption(option => option.setName("value").setDescription("USD/EUR/GBP/RON").setRequired(true)
          .addChoices(...CURRENCY_CHOICES)))
      .addSubcommand(subcommand => subcommand.setName("stores").setDescription("Filtreaza dupa magazin (steam,epic sau reset)")
        .addStringOption(option => option.setName("value").setDescription("Ex: steam,epic | reset").setRequired(true)))
      .addSubcommand(subcommand => subcommand.setName("admin-command-access").setDescription("Seteaza regula owner-only pentru roluri care pot folosi comenzi admin")
        .addRoleOption(option => option.setName("role").setDescription("Rolul permis pentru comenzi admin").setRequired(true))
        .addStringOption(option => option.setName("mode").setDescription("role = doar rolul; role-or-higher = rolul sau rol mai mare").setRequired(true)
          .addChoices({ name: "role", value: "role" }, { name: "role-or-higher", value: "role-or-higher" }))
        .addStringOption(option => option.setName("command").setDescription("Comanda/pachetul admin pentru regula (gol = global)").setRequired(false).setAutocomplete(true)))
      .addSubcommandGroup(group => group.setName("add").setDescription("Adauga in watchlist")
        .addSubcommand(subcommand => subcommand.setName("games").setDescription("Adauga un joc in watchlist")
          .addStringOption(option => option.setName("joc").setDescription("Cheia jocului").setRequired(true).setAutocomplete(true))))
      .addSubcommandGroup(group => group.setName("remove").setDescription("Scoate din watchlist")
        .addSubcommand(subcommand => subcommand.setName("games").setDescription("Scoate un joc din watchlist")
          .addStringOption(option => option.setName("joc").setDescription("Cheia jocului").setRequired(true).setAutocomplete(true))))
      .addSubcommandGroup(group => group.setName("games").setDescription("Filtru per-joc pentru update-uri")
        .addSubcommand(subcommand => subcommand.setName("reset").setDescription("Resetare filtru (toate jocurile active)")))
      .addSubcommandGroup(group => group.setName("role").setDescription("Roluri ping pentru notificari")
        .addSubcommand(subcommand => subcommand.setName("updates").setDescription("Rol pingat la update-uri (gol = oprit)")
          .addRoleOption(option => option.setName("value").setDescription("Rolul de mentionat (gol = oprit)").setRequired(false)))
        .addSubcommand(subcommand => subcommand.setName("discounts").setDescription("Rol pingat la reduceri (gol = oprit)")
          .addRoleOption(option => option.setName("value").setDescription("Rolul de mentionat (gol = oprit)").setRequired(false)))),
    new SlashCommandBuilder()
      .setName("watchlist")
      .setDescription("Gestioneaza jocurile urmarite pe server (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("show").setDescription("Afiseaza jocurile urmarite pe server"))
      .addSubcommand(subcommand => subcommand.setName("reset").setDescription("Reseteaza watchlist-ul la toate jocurile configurate"))
      .addSubcommand(subcommand => subcommand.setName("coverage").setDescription("Arata acoperirea surselor pentru jocurile urmarite")),
    new SlashCommandBuilder()
      .setName("template")
      .setDescription("Gestioneaza template-urile mesajelor botului")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("set").setDescription("Seteaza template-ul unei comenzi")
        .addStringOption(option => option.setName("command").setDescription("Comanda vizata").setRequired(true).setAutocomplete(true))
        .addStringOption(option => option.setName("text").setDescription("Template-ul nou").setRequired(true).setMaxLength(1000)))
      .addSubcommand(subcommand => subcommand.setName("reset").setDescription("Revine la template-ul implicit")
        .addStringOption(option => option.setName("command").setDescription("Comanda vizata").setRequired(true).setAutocomplete(true)))
      .addSubcommand(subcommand => subcommand.setName("status").setDescription("Arata template-ul activ si placeholder-ele")
        .addStringOption(option => option.setName("command").setDescription("Comanda vizata").setRequired(true).setAutocomplete(true))),
    new SlashCommandBuilder()
      .setName("game-alias")
      .setDescription("Gestioneaza aliasurile jocurilor pe acest server")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("add").setDescription("Adauga un alias")
        .addStringOption(option => option.setName("joc").setDescription("Jocul vizat").setRequired(true).setAutocomplete(true))
        .addStringOption(option => option.setName("alias").setDescription("Numele alternativ").setRequired(true).setMinLength(2).setMaxLength(100)))
      .addSubcommand(subcommand => subcommand.setName("remove").setDescription("Sterge un alias")
        .addStringOption(option => option.setName("joc").setDescription("Jocul vizat").setRequired(true).setAutocomplete(true))
        .addStringOption(option => option.setName("alias").setDescription("Aliasul de sters").setRequired(true).setMaxLength(100)))
      .addSubcommand(subcommand => subcommand.setName("list").setDescription("Listeaza aliasurile unui joc")
        .addStringOption(option => option.setName("joc").setDescription("Jocul vizat").setRequired(true).setAutocomplete(true))),
    new SlashCommandBuilder()
      .setName("notification")
      .setDescription("Instrumente pentru notificari")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("preview").setDescription("Previzualizeaza o notificare fara efecte secundare")
        .addStringOption(option => option.setName("command").setDescription("Comanda de notificare").setRequired(true).setAutocomplete(true))),
    new SlashCommandBuilder()
      .setName("sources")
      .setDescription("Starea surselor externe folosite de bot (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("status").setDescription("Afiseaza starea ultimelor snapshot-uri pentru surse"))
  ];
}
