import type { SlashCommandJsonSource, SlashDefinitionTools } from "./slashDefinitionTools.js";

export function buildYouTubeCommandDefinitions({ SlashCommandBuilder, PermissionsBitField }: SlashDefinitionTools): SlashCommandJsonSource[] {
  return [
    new SlashCommandBuilder()
      .setName("youtube")
      .setDescription("Urmareste canale YouTube si posteaza videoclipurile noi (admin)")
      .setDefaultMemberPermissions(PermissionsBitField.Flags.Administrator.toString())
      .addSubcommand(subcommand => subcommand.setName("subscribe").setDescription("Adauga un canal YouTube urmarit")
        .addStringOption(option => option.setName("canal").setDescription("Link, @handle sau channel ID").setRequired(true)))
      .addSubcommand(subcommand => subcommand.setName("unsubscribe").setDescription("Scoate un canal YouTube urmarit")
        .addStringOption(option => option.setName("canal").setDescription("Canalul urmarit").setRequired(true).setAutocomplete(true)))
      .addSubcommand(subcommand => subcommand.setName("list").setDescription("Listeaza canalele YouTube urmarite"))
      .addSubcommandGroup(group => group.setName("notify").setDescription("Configurarea notificarilor YouTube")
        .addSubcommand(subcommand => subcommand.setName("channel").setDescription("Seteaza canalul Discord pentru notificari")
          .addChannelOption(option => option.setName("channel").setDescription("Canalul Discord").setRequired(true)))
        .addSubcommand(subcommand => subcommand.setName("on").setDescription("Porneste notificarile YouTube"))
        .addSubcommand(subcommand => subcommand.setName("off").setDescription("Opreste notificarile YouTube"))
        .addSubcommand(subcommand => subcommand.setName("status").setDescription("Afiseaza starea notificarilor YouTube")))
      .addSubcommandGroup(group => group.setName("filter").setDescription("Filtre pentru videoclipurile YouTube")
        .addSubcommand(subcommand => subcommand.setName("shorts").setDescription("Evita sau permite YouTube Shorts")
          .addStringOption(option => option.setName("state").setDescription("on = evita Shorts").setRequired(true)
            .addChoices({ name: "on", value: "on" }, { name: "off", value: "off" })))
        .addSubcommand(subcommand => subcommand.setName("lives").setDescription("Evita sau permite livestream-uri")
          .addStringOption(option => option.setName("state").setDescription("on = evita live").setRequired(true)
            .addChoices({ name: "on", value: "on" }, { name: "off", value: "off" })))
        .addSubcommand(subcommand => subcommand.setName("premieres").setDescription("Evita sau permite premiere")
          .addStringOption(option => option.setName("state").setDescription("on = evita premiere").setRequired(true)
            .addChoices({ name: "on", value: "on" }, { name: "off", value: "off" })))
        .addSubcommand(subcommand => subcommand.setName("min-duration").setDescription("Seteaza durata minima a videoclipurilor")
          .addIntegerOption(option => option.setName("seconds").setDescription("0-86400 secunde").setRequired(true).setMinValue(0).setMaxValue(86400)))
        .addSubcommand(subcommand => subcommand.setName("status").setDescription("Afiseaza filtrele YouTube curente")))
      .addSubcommandGroup(group => group.setName("add").setDescription("Adauga rute sau cuvinte de filtru YouTube")
        .addSubcommand(subcommand => subcommand.setName("channel-route").setDescription("Adauga o ruta speciala")
          .addStringOption(option => option.setName("canal").setDescription("Canalul YouTube urmarit").setRequired(true).setAutocomplete(true))
          .addChannelOption(option => option.setName("discord").setDescription("Canalul Discord destinatie").setRequired(true)))
        .addSubcommand(subcommand => subcommand.setName("title-filter").setDescription("Adauga un cuvant sau o expresie in filtrul de titlu")
          .addStringOption(option => option.setName("word").setDescription("Titlul trebuie sa contina cel putin una dintre valori").setRequired(true).setMaxLength(100))))
      .addSubcommandGroup(group => group.setName("remove").setDescription("Sterge rute sau cuvinte de filtru YouTube")
        .addSubcommand(subcommand => subcommand.setName("channel-route").setDescription("Sterge o ruta sau toate rutele unui canal")
          .addStringOption(option => option.setName("canal").setDescription("Canalul YouTube urmarit").setRequired(true).setAutocomplete(true))
          .addStringOption(option => option.setName("discord").setDescription("Canal Discord sau toate").setRequired(true).setAutocomplete(true)))
        .addSubcommand(subcommand => subcommand.setName("title-filter").setDescription("Sterge un cuvant sau o expresie din filtrul de titlu")
          .addStringOption(option => option.setName("word").setDescription("Valoarea de sters").setRequired(true).setAutocomplete(true))))
      .addSubcommandGroup(group => group.setName("channel-route").setDescription("Rute Discord speciale pentru canalele YouTube")
        .addSubcommand(subcommand => subcommand.setName("list").setDescription("Listeaza rutele speciale")))
      .addSubcommandGroup(group => group.setName("title-filter").setDescription("Filtrul inclusiv pentru titlurile YouTube")
        .addSubcommand(subcommand => subcommand.setName("list").setDescription("Listeaza valorile filtrului inclusiv"))
        .addSubcommand(subcommand => subcommand.setName("clear").setDescription("Sterge toate valorile filtrului inclusiv")))
      .addSubcommand(subcommand => subcommand.setName("status").setDescription("Afiseaza starea completa a modulului YouTube"))
      .addSubcommand(subcommand => subcommand.setName("clear-errors").setDescription("Sterge istoricul local de erori YouTube"))
  ];
}
