export interface RuntimeIdentityEnv {
  MONGO_URI?: string;
  DISCORD_TOKEN?: string;
  DISCORD_CLIENT_ID?: string;
  REDIS_URL?: string;
  BOT_ROLE: "all" | "web" | "worker";
  DISCORD_DEV_GUILD_ID: string;
  PORT: string;
  NODE_ENV: string;
  LOG_LEVEL: string;
  isProd: boolean;
}

export interface NotificationPersistenceEnv {
  NOTIFICATION_OUTBOX_ENABLED: boolean;
  NOTIFICATION_OUTBOX_DRAIN_LIMIT: number;
  NOTIFICATION_OUTBOX_MAX_AGE_MS: number;
  NOTIFICATION_OUTBOX_RECOVERY_VERIFY: boolean;
  NOTIFICATION_OUTBOX_RECOVERY_STRICT: boolean;
  NOTIFICATION_OUTBOX_RECOVERY_HISTORY_LIMIT: number;
  NOTIFICATION_OUTBOX_SENT_TTL_HOURS: number;
  NOTIFICATION_OUTBOX_GLOBAL_ADMIN_IDS: string[];
  BOT_SENSITIVE_USER_IDS: string[];
  BOT_GLOBAL_ACCESS_CODE: string;
  BOT_GLOBAL_ACCESS_CODE_HASH: string;
  NOTIFICATION_HISTORY_TTL_DAYS: number;
  NOTIFICATION_DEAD_LETTER_REPLAY_TTL_DAYS: number;
  GUILD_SEEN_DISCOUNT_TTL_DAYS: number;
  GUILD_AUDIT_LOG_TTL_DAYS: number;
  FEEDBACK_REPORT_TTL_DAYS: number;
}

export interface NetworkRuntimeEnv {
  ALLOW_DEFAULT_PROXIES: boolean;
  TRUST_PROXY: boolean;
  TRUSTED_PROXY_COUNT: number;
  ADMIN_WEBHOOK_URL: string;
  PROXY_URLS: string;
  FETCH_CONCURRENCY: number;
  FETCH_CONCURRENCY_STEAM: number;
  FETCH_CONCURRENCY_EPIC: number;
  FETCH_CONCURRENCY_LISTING: number;
  FETCH_CONCURRENCY_DRIVER: number;
  MAX_HTML_BYTES: number;
  MAX_JSON_BYTES: number;
  MAX_DEALS: number;
  STEAM_SPECIALS_LIMIT: number;
  EPIC_SPECIALS_LIMIT: number;
  STEAM_REVIEW_BATCH_SIZE: number;
  STEAM_REVIEW_BATCH_DELAY_MS: number;
  HTTP_RATE_LIMIT_REQ: number;
  HTTP_RATE_LIMIT_WINDOW_MS: number;
}

export interface NotificationDeliveryEnv {
  METRICS_TOKEN: string;
  METRICS_PUBLIC: boolean;
  DISCORD_SEND_DELAY_MS: number;
  DISCORD_SEND_RATE_CAPACITY: number;
  DISCORD_SEND_RATE_PER_SEC: number;
  DISCORD_SEND_RATE_MAX_WAIT_MS: number;
  MAX_UPDATES_PER_CYCLE: number;
  MAX_DEALS_PER_CYCLE: number;
  GUILD_PROCESS_CONCURRENCY: number;
  SEEN_PER_GAME_LIMIT: number;
  DEALS_HISTORY_LIMIT: number;
  PENDING_UPDATES_PER_GAME_LIMIT: number;
  PENDING_DISCOUNTS_LIMIT: number;
  PENDING_UPDATE_MAX_AGE_MS: number;
  PENDING_DISCOUNT_GRACE_CYCLES: number;
  PRICE_ALERT_REARM_ABSENT_CYCLES: number;
  PENDING_UPDATE_MAX_ATTEMPTS: number;
  PENDING_DISCOUNT_MAX_ATTEMPTS: number;
}

export interface ReliabilityRuntimeEnv {
  MIGRATIONS_CONTINUE_ON_ERROR: boolean;
  MAX_FUZZY_SEARCH_INPUT: number;
  INFLIGHT_PROMISE_TIMEOUT_MS: number;
  USER_COMMAND_COOLDOWN_MS: number;
  CIRCUIT_BREAKER_FAIL_THRESHOLD: number;
  CIRCUIT_BREAKER_COOLDOWN_MS: number;
  CIRCUIT_BREAKER_JITTER_MS: number;
  SCHEMA_DRIFT_THRESHOLD: number;
  COLLECTOR_TIMEOUT_MS: number;
  HOUSEKEEPING_INTERVAL_MS: number;
  GLOBAL_HEALTH_WINDOW: number;
  GLOBAL_HEALTH_MIN_RATIO: number;
  ADMIN_ALERT_COOLDOWN_MS: number;
  SHUTDOWN_DRAIN_MS: number;
  MONGO_MAX_POOL_SIZE: number;
  MONGO_RETRY_ATTEMPTS: number;
}

export interface CacheRuntimeEnv {
  GUILD_CACHE_TTL_MS: number;
  GUILD_CACHE_MAX_SIZE: number;
  ENRICHED_DEAL_CACHE_TTL_MS: number;
  ENRICHED_DEAL_CACHE_MAX_SIZE: number;
  CACHE_TTL_MS: number;
  SINGLE_CACHE_MAX_SIZE: number;
  DLC_CACHE_MAX_SIZE: number;
  DEALS_CURRENCY_CACHE_MAX_SIZE: number;
  ITEMS_PER_PAGE: number;
  DLC_ITEMS_PER_PAGE: number;
  COMMAND_OUTPUT_MAX_CHARS: number;
}

export type RuntimeEnv = RuntimeIdentityEnv
  & NotificationPersistenceEnv
  & NetworkRuntimeEnv
  & NotificationDeliveryEnv
  & ReliabilityRuntimeEnv
  & CacheRuntimeEnv;
