import type { RuntimeEnv } from "../../types";

export const COLORS = Object.freeze({
  ERROR:    0xe74c3c,
  SUCCESS:  0x57f287,
  FREE:     0xffd700,
  INFO:     0x3498db,
  DARK:     0x2b2d31,
  DLC:      0x9b59b6,
  POSITIVE: 0x2ecc71
});

export const OP_UPDATE_OPTS = Object.freeze({ strict: false });

export function createRuntimeLimits(env: RuntimeEnv) {
  return {
    CACHE_TTL_MS: env.CACHE_TTL_MS,
    ITEMS_PER_PAGE: env.ITEMS_PER_PAGE,
    DLC_ITEMS_PER_PAGE: env.DLC_ITEMS_PER_PAGE,
    COMMAND_OUTPUT_MAX_CHARS: env.COMMAND_OUTPUT_MAX_CHARS,
    DLC_CACHE_MAX_SIZE: env.DLC_CACHE_MAX_SIZE,
    SINGLE_CACHE_MAX_SIZE: env.SINGLE_CACHE_MAX_SIZE,
    DEALS_CURRENCY_CACHE_MAX_SIZE: env.DEALS_CURRENCY_CACHE_MAX_SIZE,
    DEALS_HISTORY_LIMIT: env.DEALS_HISTORY_LIMIT,
    SEEN_PER_GAME_LIMIT: env.SEEN_PER_GAME_LIMIT,
    PENDING_UPDATES_PER_GAME_LIMIT: env.PENDING_UPDATES_PER_GAME_LIMIT,
    PENDING_DISCOUNTS_LIMIT: env.PENDING_DISCOUNTS_LIMIT,
    PENDING_UPDATE_MAX_AGE_MS: env.PENDING_UPDATE_MAX_AGE_MS,
    PENDING_DISCOUNT_GRACE_CYCLES: env.PENDING_DISCOUNT_GRACE_CYCLES,
    PRICE_ALERT_REARM_ABSENT_CYCLES: env.PRICE_ALERT_REARM_ABSENT_CYCLES,
    PENDING_UPDATE_MAX_ATTEMPTS: env.PENDING_UPDATE_MAX_ATTEMPTS,
    PENDING_DISCOUNT_MAX_ATTEMPTS: env.PENDING_DISCOUNT_MAX_ATTEMPTS,
    MAX_UPDATES_PER_CYCLE: env.MAX_UPDATES_PER_CYCLE,
    MAX_DEALS_PER_CYCLE: env.MAX_DEALS_PER_CYCLE,
    DISCORD_SEND_DELAY_MS: env.DISCORD_SEND_DELAY_MS,
    GUILD_PROCESS_CONCURRENCY: env.GUILD_PROCESS_CONCURRENCY,
    MAX_FUZZY_SEARCH_INPUT: env.MAX_FUZZY_SEARCH_INPUT,
    USER_COMMAND_COOLDOWN_MS: env.USER_COMMAND_COOLDOWN_MS,
    COLLECTOR_TIMEOUT_MS: env.COLLECTOR_TIMEOUT_MS,
    COLORS,
    OP_UPDATE_OPTS
  };
}

export type RuntimeLimits = ReturnType<typeof createRuntimeLimits>;
