[package]
name = "native-inspector"
version = "0.1.0"
edition = "2021"

[lib]
name = "native_inspector"
path = "src/lib.rs"

[[bin]]
name = "native-inspector"
path = "src/main.rs"

[dependencies]
discord_patch_bot_logic = { path = "../core" }

[target.'cfg(target_os = "linux")'.dependencies]
libseccomp = "0.4"

[target.'cfg(target_os = "linux")'.dev-dependencies]
libc = "0.2"
