import type { CommandAccessRule, CommandCatalogHelpEntry } from "./commandCatalogTypes.js";

export const NOTIFICATIONS_COMMAND_ACCESS: readonly CommandAccessRule[] = [
  { command: "latest", access: "public", discordAdminPermissions: false },
  { command: "watchlist-game", access: "public", discordAdminPermissions: false, adminRuntimeSubcommands: ["delete"] },
  { command: "start", access: "admin", discordAdminPermissions: true, sensitiveSubcommands: ["new-account-alerts", "threat-protection", "bot-add-protection"] },
  { command: "stop", access: "admin", discordAdminPermissions: true, sensitiveSubcommands: ["new-account-alerts", "threat-protection", "bot-add-protection"] },
  { command: "set", access: "admin", discordAdminPermissions: true, ownerOnlySubcommands: ["admin-command-access"], sensitiveSubcommands: ["new-account-alert-channel", "threat-alert-channel", "bot-add-alert-channel"] },
  { command: "watchlist", access: "admin", discordAdminPermissions: true },
  { command: "price-alert", access: "admin", discordAdminPermissions: true },
  { command: "future-release", access: "public", discordAdminPermissions: false, publicSubcommands: ["list"], adminRuntimeSubcommands: ["add", "delete", "start", "stop"] },
  { command: "sources", access: "admin", discordAdminPermissions: true }
];

export const NOTIFICATIONS_CATALOG_HELP: readonly CommandCatalogHelpEntry[] = [
  { command: "/set new-account-alert-channel", description: "Alege canalul pentru alertele de conturi noi.", example: "/set new-account-alert-channel canal:#security" },
  { command: "/start new-account-alerts", description: "Porneste alertele cand intra conturi noi pe server.", example: "/start new-account-alerts" },
  { command: "/stop new-account-alerts", description: "Opreste alertele pentru conturi noi.", example: "/stop new-account-alerts" },
  { command: "/set threat-alert-channel", description: "Alege canalul pentru alertele de amenintari.", example: "/set threat-alert-channel canal:#security" },
  { command: "/start threat-protection", description: "Porneste protectia la amenintari.", example: "/start threat-protection" },
  { command: "/stop threat-protection", description: "Opreste protectia la amenintari.", example: "/stop threat-protection" },
  { command: "/set bot-add-alert-channel", description: "Alege canalul pentru solicitarile si alertele de adaugare boti.", example: "/set bot-add-alert-channel canal:#security" },
  { command: "/start bot-add-protection", description: "Porneste protectia la adaugarea botilor.", example: "/start bot-add-protection" },
  { command: "/stop bot-add-protection", description: "Opreste protectia la adaugarea botilor.", example: "/stop bot-add-protection" },
  { command: "/set admin-command-access", description: "Seteaza rolul care poate folosi comenzile admin pe langa Administrator si codul global de acces. Fara command seteaza fallback-ul global; cu command seteaza regula doar pentru acea comanda sau acel pachet, de exemplu /start updates. Perechile start/stop pentru acelasi modul folosesc aceeasi regula.", example: "/set admin-command-access role:@Moderator mode:role-or-higher command:/start player-count", notes: ["Mode `role` accepta doar rolul ales, iar `role-or-higher` accepta rolul ales sau unul mai mare.", "O regula pentru `/start player-count` se aplica automat si la `/stop player-count`.", "Pana ownerul seteaza o regula de rol, rolurile nu dau acces admin; raman Administrator si codul global corect introdus prin modal ephemeral."] },
  { command: "/price-alert list", description: "Listeaza alertele de pret, pragurile, valutele si starea armata sau declansata.", example: "/price-alert list" },
  { command: "/watchlist-game add", ephemeral: true, description: "Permite unui user sa propuna un joc nou pentru lista botului. Propunerea nu activeaza jocul automat.", example: "/watchlist-game add game:silksong" },
  { command: "/watchlist-game list", ephemeral: true, description: "Afiseaza jocurile propuse de useri pentru a fi adaugate in lista botului.", example: "/watchlist-game list numar:10" },
  { command: "/watchlist-game delete", description: "Sterge un joc din lista de propuneri watchlist-game.", example: "/watchlist-game delete game:silksong" },
  { command: "/future-release add", description: "Adauga un joc care urmeaza sa apara in lista future-release a serverului. Lista are maxim 20 de jocuri.", example: "/future-release add game:silksong release-date:2026 preorder-price:indisponibil" },
  { command: "/future-release list", description: "Afiseaza jocurile future-release urmarite, data lansarii si pretul de preorder daca sunt salvate.", example: "/future-release list" },
  { command: "/future-release delete", description: "Sterge un joc din lista future-release.", example: "/future-release delete game:silksong" },
  { command: "/future-release start", description: "Configureaza canalul curent pentru notificarile future-release si marcheaza modulul activ pentru server.", example: "/future-release start" },
  { command: "/future-release stop", description: "Opreste notificarile future-release si sterge canalul salvat pentru acest modul.", example: "/future-release stop" },
  { command: "/start updates", description: "Porneste notificarile automate de update-uri pe canalul curent si face baseline, ca botul sa nu trimita retroactiv toate update-urile vechi.", example: "/start updates" },
  { command: "/start reduceri", description: "Porneste alertele automate de reduceri pe canalul curent si face baseline, ca botul sa trimita doar reducerile noi gasite dupa activare.", example: "/start reduceri" },
  { command: "/start dlc", description: "Configureaza canalul curent pentru notificarile DLC ale jocurilor active. Motorul automat DLC foloseste aceasta configuratie cand este activ in runtime.", example: "/start dlc" },
  { command: "/start player-count", description: "Adauga un joc cu Steam appId in lista de jocuri urmarite pentru topurile player-count ale serverului si salveaza canalul curent pentru acest modul.", example: "/start player-count game:cs2" },
  { command: "/stop updates", description: "Opreste notificarile automate de update-uri pentru server.", example: "/stop updates" },
  { command: "/stop reduceri", description: "Opreste alertele automate de reduceri pentru server.", example: "/stop reduceri" },
  { command: "/stop dlc", description: "Opreste notificarile DLC si sterge canalul salvat pentru acest modul.", example: "/stop dlc" },
  { command: "/stop player-count", description: "Scoate un joc din lista de player-count a serverului. Daca nu mai ramane niciun joc, modulul player-count este oprit pentru server.", example: "/stop player-count game:cs2" },
  { command: "/set mode", description: "Alege formatul embed-urilor de update: compact pentru mesaje scurte sau detailed pentru mai multe detalii.", example: "/set mode value:detailed" },
  { command: "/set mindiscount", description: "Seteaza procentul minim de reducere acceptat pentru alertele de reduceri.", example: "/set mindiscount value:50" },
  { command: "/set maxprice", description: "Seteaza pretul maxim acceptat pentru ofertele platite. Valoarea 0 dezactiveaza limita.", example: "/set maxprice value:100" },
  { command: "/set free", description: "Porneste sau opreste afisarea jocurilor gratuite in alertele de reduceri.", example: "/set free value:on" },
  { command: "/set paid", description: "Porneste sau opreste afisarea ofertelor platite in alertele de reduceri.", example: "/set paid value:on" },
  { command: "/set currency", description: "Alege valuta folosita pentru preturi si alerte de reduceri.", example: "/set currency value:EUR" },
  { command: "/set stores", description: "Filtreaza reducerile dupa magazine, de exemplu Steam si Epic, sau reseteaza filtrul.", example: "/set stores value:steam,epic" },
  { command: "/set add games", description: "Adauga un joc deja cunoscut de bot in lista explicita de jocuri active pentru server.", example: "/set add games joc:cs2", notes: ["Nu adauga un joc nou in codul botului; doar activeaza pentru server un joc existent in configuratie."] },
  { command: "/set remove games", description: "Scoate un joc din lista explicita de jocuri active pentru server.", example: "/set remove games joc:cs2" },
  { command: "/set games reset", description: "Reseteaza filtrul per-joc. Dupa reset, serverul foloseste toate jocurile cunoscute de bot.", example: "/set games reset" },
  { command: "/watchlist show", description: "Afiseaza jocurile urmarite explicit pe server. Daca lista este goala, serverul foloseste toate jocurile configurate.", example: "/watchlist show" },
  { command: "/watchlist reset", description: "Reseteaza watchlist-ul. Dupa reset, toate jocurile configurate sunt active.", example: "/watchlist reset" },
  { command: "/watchlist coverage", description: "Afiseaza pentru fiecare joc urmarit disponibilitatea update-urilor, reducerilor, server status, player-count, DLC, Steam appId si sursele configurate.", example: "/watchlist coverage" },
  { command: "/set role updates", description: "Seteaza rolul pingat la notificarile de update-uri. Daca nu alegi rol, ping-ul se opreste.", example: "/set role updates value:@Updates" },
  { command: "/set role discounts", description: "Seteaza rolul pingat la alertele de reduceri. Daca nu alegi rol, ping-ul se opreste.", example: "/set role discounts value:@Deals" },
  { command: "/latest updates", description: "Afiseaza cele mai recente update-uri pentru jocurile active ale serverului. Foloseste cache si poate folosi snapshot-ul persistat daca fetch-ul live esueaza.", example: "/latest updates" },
  { command: "/latest reduceri", description: "Afiseaza cele mai bune reduceri curente care trec filtrele serverului.", example: "/latest reduceri" },
  { command: "/latest update", description: "Cauta ultimul update pentru un joc anume.", example: "/latest update joc:cs2" },
  { command: "/latest pret", description: "Cauta pretul curent al unui joc pe Steam.", example: "/latest pret joc:Counter-Strike 2" },
  { command: "/sources status", description: "Afiseaza starea ultimelor snapshot-uri pentru sursele de date: reduceri Steam/Epic, feed-uri de update si vechimea ultimului fetch.", example: "/sources status" }
];
