export interface BotMetrics {
  fetchSuccess: number;
  fetchFail: number;
  httpRetries: number;
  rateLimitHits: number;
  cronRuns: number;
  cronErrors: number;
  cronSkippedDueToLock: number;
  cronSkippedDueToHealth: number;
  cronAborted: number;
  httpRateLimitDrops: number;
  httpHandlerErrors: number;
  outboxSent: number;
  outboxRetried: number;
  outboxDeadLettered: number;
  outboxExpired: number;
  outboxDrains: number;
  outboxQueueDepth: number;
  outboxDeliveryMsTotal: number;
  outboxOldestJobAgeSeconds: number;
  outboxFutureScheduledJobs: number;
  outboxLockAcquireFailures: number;
  outboxPauseCheckFailures: number;
  outboxRecoveryDuplicates: number;
  outboxRecoveryFetches: number;
  outboxRecoveryFailures: number;
  outboxRecoveryMarkerMissing: number;
  outboxMarkSentFailures: number;
  outboxDeleteFailures: number;
  outboxDeadLetterWriteFailures: number;
  outboxHistoryWriteFailures: number;
  outboxRecoveryVerifyEnabledGuilds: number;
  outboxLastDrainAt: number;
  redisConnectSuccess: number;
  redisConnectFailure: number;
  redisCacheHit: number;
  redisCacheMiss: number;
  redisErrors: number;
  guildSettingsListenerFailures: number;
  securityRuntimeErrors?: number;
  securityThreatsDeleted?: number;
  securityBotAddsBlocked?: number;
  permissionDelegationsReverted?: number;
  moderationCleanupRuns?: number;
  moderationCleanupFailures?: number;
  threatReputationEngineConfigured?: number;
  commandRuns: Record<string, number>;
  commandErrors: Record<string, number>;
  commandDurationMsTotal: Record<string, number>;
  startedAt: number;
}
